### ISSUE TITLE
Repeatability

### ISSUE THREAD

**Issue by kzxkzx** [rajewsky-lab/novosparc#34]
sorry to bother you, I get different results with same code in different runs, that is I cannoot get the repeatable results, especially without marker genes information.

**Comment by nukappa** [comment]
Do you use the same number of cells and genes every time? If yes, the results should be reproducible. If you change any parameters like number of cells, number of locations, number of genes used, geometry etc., the reconstructions would be of course different.

**Comment by mjang2000** [comment]
I have also not been able to repeatable results. Every time I run the tutorial notebook, I get the same results as my previous runs, but the results are not the same as the results in the tutorial notebook. I realized that the files are not named exactly the same, so I substituted missing files for the closest file (i.e. "high_var_genes.txt" instead of "hvg.txt" for the "reconstruct_drosophila_embryo_tutorial.ipynb" notebook), but other than that, I have not changed anything. I was wondering why this may be the case.

**Comment by patrickaoude** [comment]
mjang2000, I had similar issues.

Please take a look at my pull request and see if it helps: https://github.com/rajewsky-lab/novosparc/pull/21

**Comment by nukappa** [comment]
@mjang2000 @patrickaoude Thanks, we'll check this.

**Comment by enessenel** [comment]
https://github.com/rajewsky-lab/novosparc/pull/21 is merged now and the tutorial is updated with f651f2309732861625a79686618a71f393a8c359 for the correct reconstruction with marker genes. @patrickaoude thanks for the contribution!
