### ISSUE TITLE
Plot positional confidences

### ISSUE THREAD

**Issue by MalteMederacke** [rajewsky-lab/novosparc#39]
Hi,

is it possible to plot the confidence of a given single cell to be positioned at a certain physical position? 

Additionally, if I want to plot my spatial dge, I plot my physical space as a scatter plot and scale my color with the sdge matrix. Thus, if I use a legend for the expression values, they are very small, because they are the dot product from the probabilities of a cell i being a position j and the expression values, right?  Is there a way to extract the original expression values from the input dge to get a more informative legend?

Many thanks for your help!

**Comment by nukappa** [comment]
Hi @MalteMederacke,

yes, it is straightforward to plot the confidence of mapped positions. This is basically the GW matrix that is computed during the reconstruction, the sdge is simply a product of that and the DGE matrix. So you can take the GW matrix, choose the cell into consideration and plot the scores across the target space locations.

Regarding the expression values, they are small exactly as you write because the original values are multiplied with the probabilities. If you want to have more meaningful numbers (higher) you can try to normalize the sdge matrix, for instance by scaling it. It's less meaningful to obtain the original values, as multiple cells have contributed to your target space.

**Comment by MalteMederacke** [comment]
Aha! Thanks for your answer.

So in the end pl.plot_gene_patterns plots expression level probabilities for each cell, right?

**Comment by nukappa** [comment]
Yes, but over the whole tissue.
