### ISSUE TITLE
Question: Use of novosparc on tumor samples

### ISSUE THREAD

**Issue by ccruizm** [rajewsky-lab/novosparc#53]
Good day!

Thanks for developing this nice tool. Could you let me know if you have tested it on tumor samples? I saw in the last Nat Methods you used in osteosarcoma cell lines, but I want to know if you have tried it on human/mouse primary tumor tissues to see whether you can reconstruct the spatial patterning.

Thanks in advance!

**Comment by nukappa** [comment]
Hi, thanks, reconstruction of tumor samples is indeed something hard to do because of the high heterogeneity. If you apply novosparc to a primary tumor sample, it will try to bring similar cell types together - because this is its operating hypothesis under the hood. Of course that's not the case in highly heterogeneous tissues.

That being said, novosparc could still provide interesting analyses/insights in such tissues, depending on what input data you have and what question you're trying to answer. We'd recommend to start with simpler tissues though to gain intuition on novosparc's spatial reconstructions and results.

**Comment by ccruizm** [comment]
Thank you for the reply! I will try then to use some data where I expect some specific spatial organization before moving on with tumor samples.
